#!/usr/bin/env python3
"""
convert_sigma.py — convert the project's Sigma rules into queries for the Elastic lab.

  Windows rules -> EQL  (Kibana: Security -> Rules -> Create -> Event Correlation (EQL))
                   index pattern: logs-windows.sysmon_operational-*, logs-system.security-*
  Proxy rule    -> Lucene for Zeek http (ecs_zeek_beats pipeline)

    pip install sigma-cli pySigma-backend-elasticsearch
    python convert_sigma.py

Post-processing: pySigma writes regex~ "(?i)..." ; EQL's regex~ is already case-insensitive and
Lucene-style regex does not support inline flags, so "(?i)" is removed.
"""
from pathlib import Path

from sigma.backends.elasticsearch import EqlBackend, LuceneBackend
from sigma.collection import SigmaCollection
from sigma.pipelines.elasticsearch.zeek import ecs_zeek_beats
from sigma.processing.pipeline import ProcessingPipeline

HERE = Path(__file__).resolve().parent
SIGMA = HERE.parent / "sigma"
OUT = HERE.parent / "output" / "sigma_converted"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*"):
        old.unlink()
    agent = ProcessingPipeline.from_yaml((SIGMA / "pipelines" / "elastic_agent_sysmon.yml").read_text())
    rules = sorted(SIGMA.glob("*.yml")) + sorted((SIGMA / "generated").glob("*.yml"))
    summary = ["| Rule | Target | Query file |", "|---|---|---|"]
    for f in rules:
        coll = SigmaCollection.from_yaml(f.read_text(encoding="utf-8"))
        if f.name.startswith("proxy_"):
            q = LuceneBackend(ecs_zeek_beats()).convert(coll)
            target, ext = "Lucene (Zeek http)", "lucene"
        else:
            q = EqlBackend(agent).convert(coll)
            target, ext = "EQL (Elastic Agent)", "eql"
        text = "\n".join(q).replace('regex~ "(?i)', 'regex~ "')
        out = OUT / f"{f.stem}.{ext}"
        out.write_text(text + "\n", encoding="utf-8")
        summary.append(f"| {coll.rules[0].title} | {target} | `{out.name}` |")
        print(f"{f.name:60} -> {out.name}")
    (OUT / "README.md").write_text("# Converted Sigma rules\n\nGenerated by `scripts/convert_sigma.py`.\n\n"
                                   + "\n".join(summary) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
