#!/usr/bin/env python3
"""
gen_sigma_ioc_rules.py — turn the *actionable* normalised IOCs into Sigma rules (exploitation step).

Writes to ../sigma/generated/:
  dns_query_win_amadey_stealc_c2_domains.yml   (Sysmon 22 / DNS logs)
  proc_creation_win_amadey_stealc_hashes.yml   (Sysmon 1 "Hashes" field)

Only indicators with to_ids=true are used, so expired / re-assigned infrastructure never becomes a rule.
Re-run after every normalisation run. Standard library only (YAML written by hand).
"""
import json
import uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent
IN = HERE.parent / "output" / "iocs_normalized.json"
OUT = HERE.parent / "sigma" / "generated"
NS = uuid.UUID("6f1c2a3e-0d6b-4a43-9a8e-a1b2c3d4e5f6")


def yaml_list(items, indent=12):
    pad = " " * indent
    return "\n".join(f"{pad}- '{i}'" for i in items)


def main():
    data = json.loads(IN.read_text(encoding="utf-8"))
    act = [i for i in data["indicators"] if i["to_ids"]]
    domains = sorted({i["value"] for i in act if i["type"] == "domain"})
    hashes = sorted({i["value"] for i in act if i["type"] == "sha256"})
    OUT.mkdir(parents=True, exist_ok=True)
    gen = data["generated"]

    dns = f"""title: DNS Query to Known Amadey/StealC C2 Domain (generated)
id: {uuid.uuid5(NS, 'sigma-gen-dns')}
status: experimental
description: |
    Auto-generated from week-03 normalised IOCs ({len(domains)} actionable domains, as of {gen}).
    Several domains may already be sinkholed after Operation Endgame (June 2026); a query still means
    an infected host is trying to reach its C2.
references:
    - https://www.microsoft.com/en-us/security/blog/2026/06/24/stealc-and-amadey-breaking-down-infostealers-and-the-cybercrime-services-that-deliver-them/
author: Sayat Abdiraiym (AITU, Intro to Threat Hunting) - generated by gen_sigma_ioc_rules.py
date: {gen}
tags:
    - attack.command-and-control
    - attack.t1071.001
    - attack.t1568.001
logsource:
    category: dns_query
    product: windows
detection:
    selection:
        QueryName|endswith:
{yaml_list(domains)}
    condition: selection
falsepositives:
    - None expected (domains are attacker-registered); re-check after the expiry dates in iocs_normalized.csv
level: high
"""
    hsh = f"""title: Execution of Known Amadey/StealC Sample by SHA-256 (generated)
id: {uuid.uuid5(NS, 'sigma-gen-hash')}
status: experimental
description: |
    Auto-generated from week-03 normalised IOCs ({len(hashes)} SHA-256 values, as of {gen}).
    Requires Sysmon EID 1 with SHA256 in the HashType configuration.
references:
    - https://attack.mitre.org/software/S1025/
author: Sayat Abdiraiym (AITU, Intro to Threat Hunting) - generated by gen_sigma_ioc_rules.py
date: {gen}
tags:
    - attack.execution
    - attack.t1204.002
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Hashes|contains:
{yaml_list(['SHA256=' + h.upper() for h in hashes])}
    condition: selection
falsepositives:
    - None expected
level: critical
"""
    (OUT / "dns_query_win_amadey_stealc_c2_domains.yml").write_text(dns, encoding="utf-8")
    (OUT / "proc_creation_win_amadey_stealc_hashes.yml").write_text(hsh, encoding="utf-8")
    print(f"Generated 2 rules: {len(domains)} domains, {len(hashes)} hashes -> {OUT}")


if __name__ == "__main__":
    main()
